apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-as-app
  namespace: default
spec:
  type: kv-v2

  # mount path
  mount: as

  # path of the secret
  path: config/appserverdata

  # dest k8s secret
  destination:
    name: appserverdata
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: as-auth
